### ISSUE TITLE
Values.global.nodeAffinity.enable is missing

### ISSUE THREAD

**Issue by lacg** [Axway/Cloud-Automation#19]
The Values.global.nodeAffinity.enable is missing from the values.yaml chart.

I found it being defined on the Deploy-APIM-v1.0.sh under APIM/Azure/scripts on a helm install example command.

But it is missing on the values.yaml chart.

Also, I see many steps being done on this shell script, but I couldn't find any documentation and it seems very Azure centric.

**Comment by cwiechmann** [comment]
The script for the Azure deployment has not being updated for the new Helm-Chart version.

**Comment by lacg** [comment]
Thanks @cwiechmann! I will add the missing values on the values.yaml on my fork and submit a pull request for approval later next week after some test then.

**Comment by cwiechmann** [comment]
Perhaps a better idea to change the script instead of the Helm-Chart.

**Comment by lacg** [comment]
Ok, I'll let whomever uses the script to change it...
