### ISSUE TITLE
cassandra.service.port is missing

### ISSUE THREAD

**Issue by lacg** [Axway/Cloud-Automation#20]
On the apitraffic-deployment.yaml, it verifies if the Cassandra service is up and running, but the .Values.cassandra.service.port is not present on the values.yaml file. I added and it passed.

I am adding this on my fork, but if you'd like to update to everyone else for now:
cassandra:
    service:
        port: 9042

Thanks, Luiz

**Comment by cwiechmann** [comment]
I assume it only happens, when using an external Cassandra-Service. Can you confirm?

**Comment by lacg** [comment]
Hi Christoph! Yes, I confirm it happens when using an external Cassandra service.
Thanks! Luiz

**Comment by cwiechmann** [comment]
Thanks! Will be fixed with the next release.
