### ISSUE TITLE
apiportalImageTag is missing on the apiportal/_helper.tpl

### ISSUE THREAD

**Issue by lacg** [Axway/Cloud-Automation#21]
apiportalImageTag is missing on the apiportal/_helper.tpl and its respective definition will need to be included on the respective deployment for the case the user uses the global.imageTag instead of the apiportal.imageTag, just to be coherent as it is being done with the apitrafficImageTag.

Thanks, Luiz

**Comment by cwiechmann** [comment]
Thanks for the feedback @lacg. It is much appreciated.

I was thinking, it will never be required to reference the API-Portal-Image with the same Tag as ANM & API-Traffic, as the API-Portal is deployed individually. Also for that reason, I added the option to define a different Docker-Repository for the API-Portal.

However, for the matter of consistency I added this option now.
