### ISSUE TITLE
Azure blob storage key access for Minikube deploy

### ISSUE THREAD

**Issue by dokuboyejo** [Axway/Cloud-Automation#22]
Can a new key access for the minikube be made available for local test install
The current [blob](https://axwaysourcesproducts.blob.core.windows.net/helm/?sv=2019-12-12&ss=b&srt=co&sp=rlx&se=2021-12-31T21:28:20Z&st=2021-01-25T13:28:20Z&spr=https&sig=%2FeVcNlH%2BqU8l4qZefbGNxaMhxSnDysmt4fq3ZGG5dRg%3D) already expired

**Comment by cwiechmann** [comment]
@NComandini, can you perhaps help here? I'm not sure, what exactly is required.

**Comment by NComandini** [comment]
Hi @dokuboyejo,
Please use the following token to access demo images:
3mL3FoB8Pb/lqIWZwmaf3oYV2zKr0W68

I'm working also to adapt the updated helmchart for Azure.

**Comment by dokuboyejo** [comment]
@NComandini  Thanks
Where do I apply the token ... the current helm chart repo url is https://axwaysourcesproducts.blob.core.windows.net/helm/?sv=2019-12-12&ss=b&srt=co&sp=rlx&se=2021-12-31T21:28:20Z&st=2021-01-25T13:28:20Z&spr=https&sig=%2FeVcNlH%2BqU8l4qZefbGNxaMhxSnDysmt4fq3ZGG5dRg%3D

**Comment by dokuboyejo** [comment]
@cwiechmann  @NComandini  Just checking if you've update on the above.
Your timely assistance is highly appreciated

**Comment by NComandini** [comment]
Hi @dokuboyejo,
I apologize because I send you the token to pull APIM demo images.

For you information, the latest helmchart isn't updated on this repository now since the latest update.
I'm working to create a yaml example on Azure.
So please use the helmchart stored on the github repository. It remove the automatic creation of the secret object but you can create it manually to pull APIM demo images.
Many changes were done on this repo and I have to update it.  Could you tell me where did you read this command ?

**Comment by dokuboyejo** [comment]
@NComandini 
Thanks, looking forward to the Azure update
So, currently, I'm testing on minikube, and according to the [deployment guide](https://github.com/Axway/Cloud-Automation/tree/master/APIM/Minikube#deployment), the helm repo need to be added first using the now expired keys before the installing the release.
The assistance required now is to get admin node manager, api manager and api traffic running on minikube

**Comment by NComandini** [comment]
Ok, thank you for your reply.
I will update this documentation too.

**Comment by dokuboyejo** [comment]
@NComandini  Just wondering if there is a way to have the demo images easily accessible for quick local test

**Comment by NComandini** [comment]
@dokuboyejo, the minikube documentation has been updated in branch azure-example.
It has been moved on folder APIM/Helmchart/example/minikube.
This folder contains a value file example for the existing package.

Please try to use it.

**Comment by dokuboyejo** [comment]
@NComandini  Thanks.
The images are pulling through from demo registry now
The amplify discovery agent section doesn't seem to have repo url and image tag

**Comment by cwiechmann** [comment]
Hi @dokuboyejo, The Agents are currently not supported by this Helm-Chart and I strongly believe they should be part of a separate Helm-Chart. Perhaps the same, even for the API-Portal.

**Comment by dokuboyejo** [comment]
Great ... would probably use the main branch for he agent then ... thanks
