### ISSUE TITLE
License secret - axway-apim-license not mount

### ISSUE THREAD

**Issue by lmarchal88** [Axway/Cloud-Automation#24]
Hi Chris,

I provide a new license in my local_value.yaml, the secret axway-apim-license is create but I still have an error expired license when the apimgr pod started. I search in the chart but i didn't find anything related to the mount of the secret. Can you have a look at this point ?

**Comment by cwiechmann** [comment]
Thanks for reporting this issue @lmarchal88. I verified the behavior and it works perfectly fine, when providing the license correctly incl. a leading pipe:
```yaml
   license: |
      FIPS=1
      SalesForce Connector=1
      ServiceNow Connector=1
      ....
      ......
      ....
      analytics=1
      # SIGNATURE: 8eee280ede1a7fd94b91130c78da44f403f8bd9f927bc96bfd6a2a94839c049b
      # SIGNATURE: 096e86bb928c5865c77596de3814f116b9b3f4923441ac0cb8e7189f9c0f5971
```

However, the provided example was wrong, as it was missing the required `|` and this lead to the following error message:
```
cannot add license file /opt/Axway/apigateway/conf/licenses/lic.lic to set: license signature not valid
NO PRODUCT LICENSE FOUND in /opt/Axway/apigateway/conf/licenses
```

Can you please check the behavior when adding the license with a pipe?

BTW the license is mounted into the API-Manager and Traffic-Deployment:
https://github.com/Axway/Cloud-Automation/blob/87f3a040053f548dba8cafa23aa36b06e0b881d0/APIM/Helmchart/templates/apimgr/apimgr-deployment.yaml#L42-L46

and the mount:
https://github.com/Axway/Cloud-Automation/blob/87f3a040053f548dba8cafa23aa36b06e0b881d0/APIM/Helmchart/templates/apimgr/apimgr-deployment.yaml#L181-L191

**Comment by lmarchal88** [comment]
Thanks @cwiechmann it's working well with the |
