### ISSUE TITLE
API Gateway Analytics on K8S EMT architecture

### ISSUE THREAD

**Issue by dokuboyejo** [Axway/Cloud-Automation#25]
The current helmchart doesn't contain api gateway analytics for monitoring

**Comment by cwiechmann** [comment]
Hi @dokuboyejo, API-Gateway Analytics is no longer supported by Axway and therefore not part of the Helm-Chart.

**Comment by dokuboyejo** [comment]
@cwiechmann  Thanks for the feedback. What's the then the proposed strategy for monitoring and analysis

**Comment by cwiechmann** [comment]
For operational insights we propose our Elasticsearch-Integration: https://github.com/Axway-API-Management-Plus/apigateway-openlogging-elk 
and 
for business insights the Axway Amplify Analytics capabilities:
![image](https://user-images.githubusercontent.com/16292002/152785635-72cd05c5-b7bc-4fc8-8641-d6e65b05fe0d.png)

![image](https://user-images.githubusercontent.com/16292002/152785759-931ab8ca-a647-4a31-8b1c-46f1323358c9.png)
