### ISSUE TITLE
Question on Entity Store Persistence

### ISSUE THREAD

**Issue by rribei** [Axway/Cloud-Automation#31]
Hi guys,
On 7.7.20220228, There is an new functionality that allows the Entity Store to be persisted in a external storage, avoiding the need to rebake the image for each change in ES:
https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_relnotes/20220228_apimgr_relnotes/index.html
Will the Helmcharts contain the customizations for this new functionality?

**Comment by cwiechmann** [comment]
Hi @rribei, This is not yet planned and we need to check, how this can be properly incorporated into the Helm-Chart.

**Comment by cwiechmann** [comment]
Hi @rribei, 

I have release version 2.8.0 of the HELM-Chart that supports this new feature.

Check out this video that explains how you can now externalize the Policy-Configuration using the FED- or the YAML-Based-Entity-Store: 
https://github.com/Axway/Cloud-Automation/blob/master/APIM/Helmchart/README.md#deploy-policy-configuration-without-image-recreation
