### ISSUE TITLE
Invalid audit persistent volume claim name

### ISSUE THREAD

**Issue by dokuboyejo** [Axway/Cloud-Automation#34]
If audit pvc is enabled, it create a claim called `apigw-audit`
```
{{- if .Values.pvcs.audit.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apigw-audit
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/resource-policy: "keep"
spec:
{{ toYaml .Values.pvcs.audit.auditVolumeClaim | indent 2 }}
{{- end}}
```

However, the api traffic deployment sis looking for a ovc claim named `audit`
```
{{- if .Values.pvcs.audit.enabled }}
          persistentVolumeClaim:
            claimName: audit
```

I suppose the claim used in traffic deployment might need to be updated as `apigw-audit`

**Comment by dokuboyejo** [comment]
@cwiechmann  was this closed in an error?

**Comment by cwiechmann** [comment]
Thanks for reporting this issue @dokuboyejo. It has been fixed and will be delivered with the next Helm-Chart release.

**Comment by cwiechmann** [comment]
Version 2.9.0 of the Helm-Chart now contains the fix.
