### ISSUE TITLE
AuthN failure when using AdminNodeManager in HA mode

### ISSUE THREAD

**Issue by dokuboyejo** [Axway/Cloud-Automation#38]
So, it appears ANM with more than one replicas looses context of the user when performing AuthN. 
Enabling session affinity doesn't seems to make it work either

**Comment by cwiechmann** [comment]
The Admin-Node-Manager is supposed to have only ONE replica, as it's not mission critical and will be restarted when crashing.

**Comment by dokuboyejo** [comment]
@cwiechmann  I understand it might not be mission critical, however in line with [recommendation here](https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_administration/apigtw_admin/admin_node_mngr/index.html) as well as best practices, support for more than 1 replica is ideal

**Comment by cwiechmann** [comment]
The documentation is referring to a classical deployment, where it was a good advice to have a second ANM, in case ANM-1 has a failure. 
But in a Container-Platform, if the ANM goes down, a new is started immediately. 

Additionally, as you may know, when API-Traffic instances are started, they register themselves with the ANM to build the topology. If you would have 2 ANM running, the registration happens randomly at either ANM-1 or ANM-2. Each ANM will show an inconsistent view of the the current topology, which is not desired.

For example:
![image](https://user-images.githubusercontent.com/16292002/165779961-4dc1dc8d-a529-446f-a899-d66ee9a6e8b2.png)
