### ISSUE TITLE
Deployed policy is lost on new api manager pod creation

### ISSUE THREAD

**Issue by dokuboyejo** [Axway/Cloud-Automation#41]
So, there was an issue with the api manager deployment, and the entire replicaset was recreated.
Even though external database is used for the api manager, all the deployed policies were gone after recreating the replicaset

**Comment by cwiechmann** [comment]
Is the FED-Configuration baked into the image or pulled during POD-Creation?

**Comment by dokuboyejo** [comment]
@cwiechmann  been away.....
So, we're currently just deploying the policies directly and not baking it in the image

**Comment by cwiechmann** [comment]
Sure, when you deploy your Policies (FED-File) into the running POD, all deployed Policy-Changes are gone when a POD is re-created. 
Which policies are registered in the API-Manager is stored in the deployed FED-File and not in an external database.
