### ISSUE TITLE
AKS - deploy containers

### ISSUE THREAD

**Issue by SeenuMathew** [Axway/Cloud-Automation#42]
I am following the AKS install of the Axway API gateway using this procedure

https://github.com/Axway/Cloud-Automation/tree/master/APIM/Helmchart/examples/azure-aks

My pods do not start and I get the following error

XXXXXX % kubectl get all -n apim        
NAME                           READY   STATUS             RESTARTS   AGE
pod/anm-58b4c98766-9knqh       0/1     ImagePullBackOff   0          9m44s
pod/apimgr-5f6456b59f-8nm9b    0/1     Init:0/3           0          9m44s
pod/apiportal-redis-master-0   0/1     Pending            0          9m44s
pod/cassandra-0                0/1     Pending            0          9m44s
pod/mysqlapiportal-0           1/1     Running            0          9m44s
pod/mysqlmetrics-0             1/1     Running            0          9m44s
pod/portal-6b95db65b7-mj4cz    0/1     Init:1/2           0          9m44s
pod/traffic-5f45844d47-m6rsg   0/1     Init:0/3           0          9m44s
pod/traffic-5f45844d47-z8knp   0/1     Init:0/3           0          9m44s

Failed to pull image "docker-registry.demo.axway.com/demo-public/anm-demo-7.7-20211130:1.1.1": rpc error: code = Unknown desc = failed to pull and unpack image "docker-registry.demo.axway.com/demo-public/anm-demo-7.7-20211130:1.1.1": failed to resolve reference "docker-registry.demo.axway.com/demo-public/anm-demo-7.7-20211130:1.1.1": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

How do I know the list of images and tags that are available in the repository?

**Comment by cwiechmann** [comment]
This is an Axway internal repository, therefore you receive an access denied error.

The idea is, that you built you own images using the provided docker samples scripts available in the Axway-Support portal.

https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_installation/apigw_containers/index.html
