### ISSUE TITLE
Make api manager registration setting configurable via helm charts

### ISSUE THREAD

**Issue by dokuboyejo** [Axway/Cloud-Automation#43]
It would really be great to have the below api manager settings configurable via helm to make automation of environments much easier, especially the default virtual host when new instances need to be created. Other settings are also good candidate to be made configurable via helm.

![Screenshot from 2022-06-13 00-43-51](https://user-images.githubusercontent.com/969476/173256549-761b93a4-1d32-4a14-b868-f823fb4356d2.png)

![Screenshot from 2022-06-13 00-48-27](https://user-images.githubusercontent.com/969476/173256647-b3b269f0-6385-4397-90fd-ed824038bc50.png)

**Comment by cwiechmann** [comment]
Hi @dokuboyejo, To my knowledge these settings aren't controlled by any environment variables. 

The responsibility of the Helm chart should be limited to the setup of environment variables that are used by the application (e.g. the API manager) to perform required configuration. 

To realize the requirement using the Helm chart, it would be necessary to execute scripts, etc., which would increase the complexity too much.

It would be better to create a Kubernetes operator based on the APIM-CLI for this purpose, which will do the settings in the API Manager. 
Until then, the [APIM-CLI](https://github.com/Axway-API-Management-Plus/apim-cli) can be used externally (maybe based on a CI/CD-Pipeline) to provide the environment with [configuration](https://github.com/Axway-API-Management-Plus/apim-cli/wiki/6.-API-Manager-Settings) after the HELM installation.
