### ISSUE TITLE
Cassandra version proposed on Chart.yaml is archived

### ISSUE THREAD

**Issue by ramonpenteado** [Axway/Cloud-Automation#44]
Apparently we can not run `helm dep update` as chart version 7.7 is archived and deprecated. The only versions possible to use is 9.x.x and forward.

**Comment by cwiechmann** [comment]
Hi @ramonpenteado, But the chart itself is still deploy-able. Can you please confirm?

**Comment by ramonpenteado** [comment]
@cwiechmann yes. Sorry. I wasn't clear about it. I was just wondering if we could use the supported version or anything like that.

**Comment by NComandini** [comment]
This problem blocks the creation of new package release on this repo. 
It blocks also customers that want to create their own helm package based on this one.
Bitnami has deleted previous helm version compatible with Cassandra v3.11.x.

**Comment by NComandini** [comment]
Problem solved by using another repo that contains the reference.
