### ISSUE TITLE
Support Resource Quota

### ISSUE THREAD

**Issue by dokuboyejo** [Axway/Cloud-Automation#45]
Currently, the resource specification (resource.limit and resource.request) specified in the helm values aren't fully propagated to pod configuration for each deployment, and making resource quota at the namespace level not possible.

**Comment by dokuboyejo** [comment]
@NComandini  Thanks
So, a good way to test this is to create resource quota for the namespace where ANM,APIMGR,APITRAFFIC, and APIPORTAL are installed. Without the underlying helm template ensuring all necessary resources uses resource.limit and resource.request, the scheduling of the deployments doesn't get triggered

**Comment by NComandini** [comment]
Ok, thank you for the precision.
If I resume, your problem is a that ResourceQuota is a missing in the existing helm. 
We have to add that but values must be defined by user.

Usage of limitRange isn't possible because our components don't consume the same amount of resources. 
So It won't be added on the helmchart.

**Comment by dokuboyejo** [comment]
@NComandini  It can be parameterized I suppose for resource quota usage

**Comment by NComandini** [comment]
Hello @dokuboyejo,
Axway has published an official Helm chart with dockers images (November release).
Please consult this documentation : https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_howto_guides/container_helm_deployment/index.html

As discussed in this flow, you can create yourself the object.
I've added the idea here : https://amplifyideas.axway.com/ideas/APIG-I-1186
