### ISSUE TITLE
ANM not working with mergedir

### ISSUE THREAD

**Issue by dokuboyejo** [Axway/Cloud-Automation#47]
When using the mergedir, below error is display when the service start

ERROR: Cannot use configuration in /merge/fed: product is NodeManager, FED productKey is 'VordelGateway'

**Comment by dokuboyejo** [comment]
Had conflict which has now been resolved

**Comment by NComandini** [comment]
Perfect.
Could you take few minutes to explain the cause and your resolution please ? 
I'm sure it will be interesting for others.
