### ISSUE TITLE
[FEATURE] Stream logs to operational analytics

### ISSUE THREAD

**Issue by NComandini** [Axway/Cloud-Automation#48]
**Is your feature request related to a problem? Please describe.**
According to the architecture pattern of the operational Analytics component, the filebeat component must be present on the APIM deployment in 2 cases : 
- APIM and Operational Analytics is managed by a different team
- APIM and Operational Analytics isn't on the same cluster.

**Describe the solution you'd like**
The filebeat component with the default configuration extracted from the repository [apigateway-openlogging-elk](https://github.com/Axway-API-Management-Plus/apigateway-openlogging-elk/tree/develop/helm)
The idea is to add an additional container on each APIM pods with default resources by default.
Many benefits for that : 
- They share the same context
- It's really adapted for high volumetry
- Risk to lost data is minimal
- It avoid to use shared storage

**Describe alternatives you've considered**
Use extra values in the existing helm is possible but it's really complex. Also, Operational Analytics is an optional component and his deployment must be standardized.

**Comment by cwiechmann** [comment]
Have you seen this example? It adds an additional container to the API-Gateway PODS that runs Filebeat along the gateways:

https://github.com/Axway-API-Management-Plus/axway-api-management-automated/blob/main/helm/aws-eks/axway-apim-on-aws-eks-values.yaml

**Comment by NComandini** [comment]
Yes, I saw that example.
Filebeat is a standard tool between APIM and the Operational Insights.
So I think it must be added by default in the helm for a simpler usage like mysql, redis, etc.

I know it duplicate some configuration file but the apigateway-openlogging-elk project will be always the master that drive any changes.
