### ISSUE TITLE
[FEATURE] - ConfigMap for envsettings.props

### ISSUE THREAD

**Issue by ramonpenteado** [Axway/Cloud-Automation#49]
**Is your feature request related to a problem? Please describe.**
For OBB we need to externalize our envsttings.props file. This is important as we inform api gateway some backend endpoints there.

**Describe the solution you'd like**
A root option to externalize or not the envsettings.props

**Describe alternatives you've considered**
Needs a external volume mount to be provided based on a configmap that hosts the envsettings.props file and flag that decides either it will be deployed or not.

**Additional context**

**Comment by NComandini** [comment]
@ramonpenteado envsettings.props can be externalized on components Admin Node Manager, APi Manager and Gateways.
I've implemented the capability to add additional lines in any of them.
